# Turn off email notifications
notifications:
  email: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  # Run tests
  - yarn test:ci
  # Report coverage
  - yarn coveralls
  # Linting command. Fail if there is something wrong with linting
  - yarn lint
  # Run production build
  - yarn build